### ISSUE TITLE
Bug: When saving note modfiers revert to normal

### ISSUE THREAD

**Issue by GenericName360** [komdog/BBCharter#15]
### Discord ID

GenericName#9797

### What happened?

When saving the chart note modifiers reverted to a normal note type. that is from a ghost note into a regular note, or an auto note into a regular note.

### What was the expected behvaior?

I expected it to preserve the current note modifier

### What OS are you seeing the problem on?

Windows

**Comment by komdog** [comment]
I can't reproduce this bug. The notes are preserved when I save them.

https://user-images.githubusercontent.com/42328288/236444937-5215411c-d6e4-48bf-8307-af0299df4072.mp4
